# Module = 2

# Data Maipulation with pandas

##Series

In [ ]:
import pandas as pd
marks = [6,10,12,16,28]
DS = pd.Series(marks)
print((DS))

0     6
1    10
2    12
3    16
4    28
dtype: int64

In [ ]:
import pandas as pd
marks = [6,10,12,16,28]
DS = pd.Series(marks)
DS

0     6
1    10
2    12
3    16
4    28
dtype: int64

In [ ]:
import pandas as pd
marks = [6,10,12,16,28] #custmize index
DS = pd.Series(marks,index = ["A","B","C","D","E"])
print(DS)

A     6
B    10
C    12
D    16
E    28
dtype: int64

In [ ]:
import pandas as pd
marks = [6,10,12,16,28] #custmize index
DS = pd.Series(marks,index = ["A","B","C","D"])# length of values does not match length of index)(4)
print(DS)

ValueError: Length of values (5) does not match length of index (4)

In [ ]:
import pandas as pd
marks = [6,10,12,16,28] #custmize index
DS = pd.Series(marks,index = ["A","B","C","D","E","F"])#length of values(5) does not match length of index)(6)
print(DS)

ValueError: Length of values (5) does not match length of index (6)

##index and slicing

In [ ]:
print("access element by int" ,DS ["A"])

access element by int 6

In [ ]:
print("access element by varible = a,b,c," ,DS ["A"])

access element by varible = a,b,c, 6

In [ ]:
print("Slicing in Series",DS[0:3])

Slicing in Series A     6
B    10
C    12
dtype: int64

In [ ]:
print("Slicing in Series",DS['A':'D'])

Slicing in Series A     6
B    10
C    12
D    16
dtype: int64

In [ ]:
marks = [6,10,12,16,28] #custmize index
DS = pd.Series(marks,index = ["A","B","C","D","E"])
print(DS)

print("slicing in series " ,DS["A": "C"])

A     6
B    10
C    12
D    16
E    28
dtype: int64
slicing in series  A     6
B    10
C    12
dtype: int64

## Series operation

In [ ]:
marks = [6,10,12,16,28] #custmize index
DS = pd.Series(marks,index = ["A","B","C","D","E"])
print(DS.sum())

72

In [ ]:
print(DS.mean())

14.4

In [ ]:
print(DS.max())

28

In [ ]:
print(DS.min())

6

## vectorized operator

In [ ]:
DS*3

A    18
B    30
C    36
D    48
E    84
dtype: int64

In [ ]:
DS+2

A     8
B    12
C    14
D    18
E    30
dtype: int64

In [ ]:
DS -4

A     2
B     6
C     8
D    12
E    24
dtype: int64

In [ ]:
DS /2

A     3.0
B     5.0
C     6.0
D     8.0
E    14.0
dtype: float64

In [ ]:
DS %5

A    1
B    0
C    2
D    1
E    3
dtype: int64

In [ ]:
DS **3

A      216
B     1000
C     1728
D     4096
E    21952
dtype: int64

In [ ]:
import pandas as pd
# dict can be a series
info = {
    "name" : "geetanjali",
    'age' : 19,
    'marks' : [96,88,80.,54,]

}
DS1 = pd.Series(info)
print(DS1)

name             geetanjali
age                      19
marks    [96, 88, 80.0, 54]
dtype: object

In [ ]:
DS1.index

Index(['name', 'age', 'marks'], dtype='object')

In [ ]:
(DS1["name"])

'geetanjali'

# Create a series with single digit

In [ ]:
num = pd.Series(10)
print(num)

0    10
dtype: int64

In [ ]:
# we can create multi ple index with single values
num = pd.Series(10,index = [1,2,3,4,5])
print(num)

1    10
2    10
3    10
4    10
5    10
dtype: int64

In [ ]:
# addition of basic index
num1 = pd.Series(10,index = [1,2,3,4,5])
num2 = pd.Series(20,index = [6,2,0,8,9])
#nan = not a number
'''same index  additon will perform
but in case differnet index it will show NaN
'''
print(num1 + num2)

0     NaN
1     NaN
2    30.0
3     NaN
4     NaN
5     NaN
6     NaN
8     NaN
9     NaN
dtype: float64

In [ ]:
num1 = pd.Series(10,index = [1,2,3,4,5])
num2 = pd.Series(20,index = [1,2,3,4,5])
print(num1 + num2)

1    30
2    30
3    30
4    30
5    30
dtype: int64

In [ ]:
num1 = pd.Series(10,index = [1,2,3,4,5])
num2 = pd.Series(20,index = ["a","b","c","d","e"])
print(num1 + num2)

1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
dtype: float64

## 2. main data structure

## Pandas DataFrame

In [ ]:
student={
    'Name':['Pragya','Payal','Niahrika'],
    'Roll no.':[70,67,62],
    'Marks':[92,93,95]
}

df=pd.DataFrame(student)
print(df)

       Name  Roll no.  Marks
0    Pragya        70     92
1     Payal        67     93
2  Niahrika        62     95

In [ ]:
# All arrays must be of the same length
student={
    'Name':['Pragya','Payal','Niahrika'],
    'Roll no.':[70,67,62],
    'Marks':[93,95]    #ValueError: All arrays must be of the same length
}

df=pd.DataFrame(student)
print(df)

ValueError: All arrays must be of the same length

In [ ]:
# Creating a dataframe with list

student_info=[['a','b','c'],[20,30,40]]
df=pd.DataFrame(student_info)
df
#print(df)

    0   1   2
0   a   b   c
1  20  30  40

In [ ]:
 #Creating dataframe with multiple series

 SR={
     'Name':pd.Series(['Pragya','Niharika','Payal']),
     'Roll no':pd.Series([70,67,62])
 }
 df=pd.DataFrame(SR)
df

       Name  Roll no
0    Pragya       70
1  Niharika       67
2     Payal       62

##Arithmetic Opeartions

In [ ]:
var=pd.DataFrame({'A':[1,2,3],'B':[3,5,6]})
var

   A  B
0  1  3
1  2  5
2  3  6

In [ ]:
var["C"]=var['A']+var['B']
var

   A  B  C
0  1  3  4
1  2  5  7
2  3  6  9

## Sorting

In [ ]:
#filter
var['Python']=var["C"]>10
var

   A  B  C  Python
0  1  3  4   False
1  2  5  7   False
2  3  6  9   False

##  hiding missing values

In [ ]:
# create a dict. using np.NaN
#
import numpy as np
student={
    'Name':['Pragya','Payal','Niharika','Chhavi','Sarthak'],
    'Roll no.':[70,67,62,34,np.nan],
    'Marks':[92,93,np.nan,98,99],
    'Subject':['Chem',np.nan,'BIO',np.nan,'physics'],
    'City':['noida','noida','siwan',np.nan,np.nan]
}

df=pd.DataFrame(student)
df

       Name  Roll no.  Marks  Subject   City
0    Pragya      70.0   92.0     Chem  noida
1     Payal      67.0   93.0      NaN  noida
2  Niharika      62.0    NaN      BIO  siwan
3    Chhavi      34.0   98.0      NaN    NaN
4   Sarthak       NaN   99.0  physics    NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      5 non-null      object
 1   Roll no.  4 non-null      float64
 2   Marks     4 non-null      float64
 3   Subject   3 non-null      object
 4   City      3 non-null      object
dtypes: float64(2), object(3)
memory usage: 332.0+ bytes

In [ ]:
df.isnull()

    Name  Roll no.  Marks  Subject   City
0  False     False  False    False  False
1  False     False  False     True  False
2  False     False   True    False  False
3  False     False  False     True   True
4  False      True  False    False   True

In [ ]:
df.isnull().sum()

Name        0
Roll no.    1
Marks       1
Subject     2
City        2
dtype: int64

In [ ]:
print(df.isnull().sum().sum())

6

In [ ]:
df.dropna()

     Name  Roll no.  Marks Subject   City
0  Pragya      70.0   92.0    Chem  noida

In [ ]:
df['Marks']=df['Marks'].fillna(0)

In [ ]:
df.dropna(subset=['Roll no.'])

       Name  Roll no.  Marks Subject   City
0    Pragya      70.0   92.0    Chem  noida
1     Payal      67.0   93.0     NaN  noida
2  Niharika      62.0    0.0     BIO  siwan
3    Chhavi      34.0   98.0     NaN    NaN

In [ ]:
df['Marks']=df['Marks'].fillna(df['Marks'].mean())
print(df['Marks'])

0    92.0
1    93.0
2     0.0
3    98.0
4    99.0
Name: Marks, dtype: float64

In [ ]:
df['Name'].fillna("unknown")

0      Pragya
1       Payal
2    Niharika
3      Chhavi
4     Sarthak
Name: Name, dtype: object

#Chapter = 2,Data cleaning and transformation

In [ ]:
from google.colab import files
upload=files.upload()

Saving penguins (1).csv to penguins (1).csv

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/penguins (1).csv")
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [ ]:
df.head(5)
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [ ]:
# check data types and missing values count
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                334 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

In [ ]:
# check   missing values
df.isnull()
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [ ]:
# check total missing values per column
df.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  10
dtype: int64

In [ ]:
# get statistical summary of  numerical columns
df.describe()
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [ ]:
df.columns

Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex'],
      dtype='object')

In [ ]:
# count dublicates row and remove
# count dublicates row
print("duplicate value:\n", df.duplicated().sum())
# remove duplicates row
df.drop_duplicates(inplace= True)

duplicate value:
 0

#chapter = 3, merging and joining dataframe

#merge

In [ ]:
import pandas as  pd
df1 = pd.DataFrame({"A":[2,3,4,5], "B":["A","B","C","D"]})
df2 = pd.DataFrame({"A":[2,4,6,8], "B":["A","C","E","F"]})
pd.merge(df1,df2)

   A  B
0  2  A
1  4  C

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A":[2,3,4,5], "B":["A","B","C","D"]})
df2 = pd.DataFrame({"A":[2,4,6,8], "B":["A","C","E","F"]})
df3 = pd.merge(df1,df2)
print(df3)

   A  B
0  2  A
1  4  C

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A":[2,3,4,5], "B":["A","B","D"]}) # get error if first column has 4 values and second column has 3 values
df2 = pd.DataFrame({"A":[2,4,6,8], "B":["A","C","E","F"]})
pd.merge(df1,df2)

ValueError: All arrays must be of the same length

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A":[2,3,4,5], "B":["A","B","C","D"]})
df2 = pd.DataFrame({"A":[2,4,6,8], "C":["A","C","E","F"]})
pd.merge(df1,df2)

   A  B  C
0  2  A  A
1  4  C  C

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A":[2,3,4,5], "B":["A","B","C","D"]})
df2 = pd.DataFrame({"A":[2,4,6,8], "B":["A","C","E","F"]})
pd.merge(df1,df2, on= ('A'),how ='inner')

   A B_x B_y
0  2   A   A
1  4   C   C

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A":[2,3,4,5], "B":["A","B","C","D"]})
df2 = pd.DataFrame({"A":[2,4,6,8], "C":["A","C","E","F"]})
pd.merge(df1,df2,on = ('A'),how = 'outer')

   A    B    C
0  2    A    A
1  3    B  NaN
2  4    C    C
3  5    D  NaN
4  6  NaN    E
5  8  NaN    F

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A":[2,3,4,5], "B":["A","B","C","D"]})
df2 = pd.DataFrame({"A":[2,4,6,8], "C":["A","C","E","F"]})
pd.merge(df1,df2,on = ('A'),how = 'left')

   A  B    C
0  2  A    A
1  3  B  NaN
2  4  C    C
3  5  D  NaN

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A":[2,3,4,5], "B":["A","B","C","D"]})
df2 = pd.DataFrame({"A":[2,4,6,8], "C":["A","C","E","F"]})
pd.merge(df1,df2,on = ('A'),how = 'right')

   A    B  C
0  2    A  A
1  4    C  C
2  6  NaN  E
3  8  NaN  F

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A":[1,2,3,4,], "B":[10,20,30,40]})
df2 = pd.DataFrame({"A":[1,2,3,4], "B":[100,200,300,400]})
pd.merge(df1,df2)

Empty DataFrame
Columns: [A, B]
Index: []

In [ ]:

df1 = pd.DataFrame({"A":[1,2,3,4,], "B":[10,20,30,40]})
df2 = pd.DataFrame({"A":[1,2,3,4], "B":[100,200,300,400]})
pd.merge(df1,df2,on = ('A'),how= 'inner')

   A  B_x  B_y
0  1   10  100
1  2   20  200
2  3   30  300
3  4   40  400

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A":[2,3,4,5], "B":["A","B","C","D"]})
df2 = pd.DataFrame({"A":[2,3,4,5], "C":["E","F","G","H"]})
pd.merge(df1,df2,on = ('A'),how = 'left')

   A  B  C
0  2  A  E
1  3  B  F
2  4  C  G
3  5  D  H

In [ ]:
df1 = pd.DataFrame({"roll_no":[12,13,14],"name":["A","B","C"]})
df2 = pd.DataFrame({"roll_no":[15,16,17],"name": ["E","F","G"]})
df3 = pd.merge(df1,df2)
print(df3)

Empty DataFrame
Columns: [roll_no, name]
Index: []

In [ ]:
df1 = pd.DataFrame({"roll_no":[12,13,14],"name":["A","B","C"]})
df2 = pd.DataFrame({"roll_no":[15,16,17],"name": ["E","F","G"]})
pd.merge(df1,df2)

Empty DataFrame
Columns: [roll_no, name]
Index: []

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"roll":[12,13,14,15], "Name":["hanshi","shivi","harsh","vansh"]})
df2 = pd.DataFrame({"roll":[16,17,18,19], "Name":["sagar","ashi","Geetika","Harshita"]})
pd.merge(df1,df2,on ='roll',how = 'left')

   roll  Name_x Name_y
0    12  hanshi    NaN
1    13   shivi    NaN
2    14   harsh    NaN
3    15   vansh    NaN

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"roll":[12,13,14,15], "Name":["hanshi","shivi","harsh","vansh"]})
df2 = pd.DataFrame({"roll":[16,17,18,19], "Name":["sagar","ashi","Geetika","Harshita"]})
pd.merge(df1,df2,on = 'roll',how = 'right')

   roll Name_x    Name_y
0    16    NaN     sagar
1    17    NaN      ashi
2    18    NaN   Geetika
3    19    NaN  Harshita

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"roll":[12,13,14,15], "Name":["hanshi","shivi","harsh","vansh"]})
df2 = pd.DataFrame({"roll":[16,17,18,19], "Name":["sagar","ashi","Geetika","Harshita"]})
pd.merge(df1,df2,how = 'inner')

Empty DataFrame
Columns: [roll, Name]
Index: []

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"roll":[12,13,14,15], "Name":["hanshi","shivi","harsh","vansh"]})
df2 = pd.DataFrame({"roll":[16,17,18,19], "Name":["sagar","ashi","Geetika","Harshita"]})
pd.merge(df1,df2,how = 'outer')

   roll      Name
0    12    hanshi
1    13     shivi
2    14     harsh
3    15     vansh
4    16     sagar
5    17      ashi
6    18   Geetika
7    19  Harshita

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"roll":[12,13,14,15], "Name":["hanshi","shivi","harsh","vansh"]})
df2 = pd.DataFrame({"roll":[16,17,18,19], "Name":["sagar","ashi","Geetika","Harshita"]})
pd.merge(df1,df2,how = 'outer',indicator= True)

   roll      Name      _merge
0    12    hanshi   left_only
1    13     shivi   left_only
2    14     harsh   left_only
3    15     vansh   left_only
4    16     sagar  right_only
5    17      ashi  right_only
6    18   Geetika  right_only
7    19  Harshita  right_only

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"roll":[12,13,14,15], "Name":["hanshi","shivi","harsh","vansh"]})
df2 = pd.DataFrame({"roll":[16,17,18,19], "Name":["sagar","ashi","Geetika","Harshita"]})
pd.merge(df1,df2,how = 'outer',right_index=  True,left_index=True)

   roll_x  Name_x  roll_y    Name_y
0      12  hanshi      16     sagar
1      13   shivi      17      ashi
2      14   harsh      18   Geetika
3      15   vansh      19  Harshita

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"roll":[12,13,14,15], "Name":["hanshi","shivi","harsh","vansh"]})
df2 = pd.DataFrame({"roll":[16,17,18,19], "Name":["sagar","ashi","Geetika","Harshita"]})
pd.merge(df1,df2,right_index=  True,left_index=True)

   roll_x  Name_x  roll_y    Name_y
0      12  hanshi      16     sagar
1      13   shivi      17      ashi
2      14   harsh      18   Geetika
3      15   vansh      19  Harshita

In [ ]:
import pandas as pd
_9 = pd.DataFrame({"roll":[1,2,3,4], "Name":["hanshi","shivi","harsh","vansh"]})
_10= pd.DataFrame({"roll":[1,2,3,4], "Name":["geetika","ashi","anjali","Harshita"]})
pd.merge(_9,_10,how = 'outer',right_index=True,left_index=True)

   roll_x  Name_x  roll_y    Name_y
0       1  hanshi       1   geetika
1       2   shivi       2      ashi
2       3   harsh       3    anjali
3       4   vansh       4  Harshita

In [ ]:
import pandas as pd
_9 = pd.DataFrame({"roll":[1,2,3,4], "Name":["hanshi","shivi","harsh","vansh"]})
_10= pd.DataFrame({"roll":[1,2,3,4], "Name":["geetika","ashi","anjali","Harshita"]})
pd.merge(_9,_10,how = 'outer',suffixes=('_9','_10'),right_index=True,left_index=True)

   roll_9  Name_9  roll_10   Name_10
0       1  hanshi        1   geetika
1       2   shivi        2      ashi
2       3   harsh        3    anjali
3       4   vansh        4  Harshita

#join

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A":[2,3,4,5], "B":["A","B","C","D"]})
df2 = pd.DataFrame({"D":[2,4,6,8], "C":["A","C","E","F"]})
df1.join(df2)

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A":[2,3,4,5], "B":["A","B","C","D"]},index= [1,2,3,4])
df2 = pd.DataFrame({"D":[2,3,4,5], "C":["A","C","E","F"]})
df1.join(df2)

   A  B    D    C
1  2  A  3.0    C
2  3  B  4.0    E
3  4  C  5.0    F
4  5  D  NaN  NaN

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A":[2,3,4,5], "B":["A","B","C","D"]},index= ["a","b","c","d"])
df2 = pd.DataFrame({"D":[2,3,4,5], "C":["A","C","E","F"]},index= ["a","b","c","d"])
df1.join(df2)

   A  B  D  C
a  2  A  2  A
b  3  B  3  C
c  4  C  4  E
d  5  D  5  F

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A":[1,2,3,4,5], "C":["A","B","C","D","E"]},index= ["a","b","c","d","e"])
df2 = pd.DataFrame({"B":[6,7], "D":["A","D"]},index=["f","g"])
df1.join(df2)

   A  C   B    D
a  1  A NaN  NaN
b  2  B NaN  NaN
c  3  C NaN  NaN
d  4  D NaN  NaN
e  5  E NaN  NaN

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A":[2,3,4,5], "C":["A","B","C","D"]},index= ["a","b","c","d"])
df2 = pd.DataFrame({"B":[6,7], "D":["A","D"]},index=["e","f"])
df2.join(df1)

   B  D   A    C
e  6  A NaN  NaN
f  7  D NaN  NaN

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A":[1,2,3,4,5], "C":["A","B","C","D","E"]},index= ["a","b","c","d","e"])
df2 = pd.DataFrame({"B":[6,7], "D":["A","D"]},index=["f","g"])
df1.join(df2,how = 'inner')

Empty DataFrame
Columns: [A, C, B, D]
Index: []

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A":[1,2,3,4,5], "C":["A","B","C","D","E"]},index= ["a","b","c","d","e"])
df2 = pd.DataFrame({"B":[6,7], "D":["A","D"]},index=["f","g"])
df1.join(df2,how = 'left')

   A  C   B    D
a  1  A NaN  NaN
b  2  B NaN  NaN
c  3  C NaN  NaN
d  4  D NaN  NaN
e  5  E NaN  NaN

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A":[1,2,3,4,5], "C":["A","B","C","D","E"]},index= ["a","b","c","d","e"])
df2 = pd.DataFrame({"B":[6,7], "D":["A","D"]},index=["f","g"])
df1.join(df2,how= 'right')

    A    C  B  D
f NaN  NaN  6  A
g NaN  NaN  7  D

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A":[1,2,3,4,5], "C":["A","B","C","D","E"]},index= ["a","b","c","d","e"])
df2 = pd.DataFrame({"B":[6,7], "D":["A","D"]},index=["f","g"])
df1.join(df2,how = 'outer')

     A    C    B    D
a  1.0    A  NaN  NaN
b  2.0    B  NaN  NaN
c  3.0    C  NaN  NaN
d  4.0    D  NaN  NaN
e  5.0    E  NaN  NaN
f  NaN  NaN  6.0    A
g  NaN  NaN  7.0    D

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A":[1,2,3,4,5], "C":["A","B","C","D","E"]},index= ["a","b","c","d","e"])
df2 = pd.DataFrame({"A":[6,7], "D":["A","D"]},index=["f","g"])
df1.join(df2)

ValueError: columns overlap but no suffix specified: Index(['A'], dtype='object')

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A":[1,2,3,4,5], "C":["A","B","C","D","E"]},index= ["a","b","c","d","e"])
df2 = pd.DataFrame({"B":[6,7], "D":["A","D"]},index=["f","g"])
df1.join(df2,lsuffix='_left')

   A  C   B    D
a  1  A NaN  NaN
b  2  B NaN  NaN
c  3  C NaN  NaN
d  4  D NaN  NaN
e  5  E NaN  NaN

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A":[1,2,3,4,5], "C":["A","B","C","D","E"]},index= ["a","b","c","d","e"])
df2 = pd.DataFrame({"B":[6,7], "D":["A","D"]},index=["f","g"])
df1.join(df2,lsuffix='_right')

   A  C   B    D
a  1  A NaN  NaN
b  2  B NaN  NaN
c  3  C NaN  NaN
d  4  D NaN  NaN
e  5  E NaN  NaN

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A":[1,2,3,4], "B":["A","B","C","D"]})
df2 = pd.DataFrame({"B":[5,6,7,8], "C":["E","F","G","H"]})
df3 = pd.DataFrame({"E":[9,10,11,12],"F":["I","J","k","L"]})
df1.join([df2,df3])# overlapping

ValueError: Indexes have overlapping values: Index(['B'], dtype='object')

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A":[1,2,3,4], "B":["A","B","C","D"]})
df2 = pd.DataFrame({"D":[5,6,7,8], "C":["E","F","G","H"]})
df3 = pd.DataFrame({"E":[9,10,11,12],"F":["I","J","k","L"]})
df1.join(df2).join(df3)

   A  B  D  C   E  F
0  1  A  5  E   9  I
1  2  B  6  F  10  J
2  3  C  7  G  11  k
3  4  D  8  H  12  L

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"name":["payal","shivi","hanshi","depanshi","harsh"],"rollno":[6061,6062,6063,6064,6065],"ID":["E2","E3","E4","E4","E5"]})
df2  = pd.DataFrame({"marks":[99,98,97,56,45],"subject":["ches","bio","math","phy","eng"]})
df1.join(df2)

       name  rollno  ID  marks subject
0     payal    6061  E2     99    ches
1     shivi    6062  E3     98     bio
2    hanshi    6063  E4     97    math
3  depanshi    6064  E4     56     phy
4     harsh    6065  E5     45     eng

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A":[1,2,3,4], "B":["A","B","C","D"]})
df2 = pd.DataFrame({"D":[5,6,7,8], "C":["E","F","G","H"]})
df3 = pd.DataFrame({"E":[9,10,11,12],"F":["I","J","k","L"]})

df4 = pd.DataFrame({"G":[13,14,15,17],"H":["M","N","O","P"]})
df5 =df1.join([df2,df3])
df5.join(df4)

   A  B  D  C   E  F   G  H
0  1  A  5  E   9  I  13  M
1  2  B  6  F  10  J  14  N
2  3  C  7  G  11  k  15  O
3  4  D  8  H  12  L  17  P

#Concat

In [ ]:
import pandas as pd

In [ ]:
rollno =pd.Series([6061,6062,6063,6064,6065])
rollno2 =pd.Series([6061,6062,6063,6064,6065])
pd.concat([rollno,rollno2],axis=0)

0    6061
1    6062
2    6063
3    6064
4    6065
0    6061
1    6062
2    6063
3    6064
4    6065
dtype: int64

In [ ]:
rollno =pd.Series([6061,6062,6063,6064,6065])
rollno2 =pd.Series([6061,6062,6063,6064,6065])
pd.concat([rollno,rollno2],axis=1)

      0     1
0  6061  6061
1  6062  6062
2  6063  6063
3  6064  6064
4  6065  6065

In [ ]:
rollno =pd.Series([6061,6062,6063,6064,6065])
rollno2 =pd.Series([6061,6062,6063,6064,6065])
pd.concat([rollno,rollno2],axis=0,ignore_index= True)

0    6061
1    6062
2    6063
3    6064
4    6065
5    6061
6    6062
7    6063
8    6064
9    6065
dtype: int64

In [ ]:
rollno =pd.Series([6061,6062,6063,6064,6065])
rollno2 =pd.Series([6061,6062,6063,6064,6065])
pd.concat([rollno,rollno2],axis=0,ignore_index= False )

0    6061
1    6062
2    6063
3    6064
4    6065
0    6061
1    6062
2    6063
3    6064
4    6065
dtype: int64

In [ ]:
df1 = pd.DataFrame({"A":[2,3,4,5], "B":["AC","BI","C","D"]})
df2 = pd.DataFrame({"A":[2,3,4,5], "B":["AT","C","EG","F"]})
pd.concat([df1,df2],ignore_index=True)

   A   B
0  2  AC
1  3  BI
2  4   C
3  5   D
4  2  AT
5  3   C
6  4  EG
7  5   F

In [ ]:
df1 = pd.DataFrame({"A":[2,3,4,5], "B":["A","B","C","D"]})
df2 = pd.DataFrame({"A":[2,3,4,5], "B":["A","C","E","F"]})
pd.concat([df1,df2],how = 'right')#

TypeError: concat() got an unexpected keyword argument 'how'

In [ ]:
df1 = pd.DataFrame({"A":[2,3,4,5], "B":["A","B","C","D"]})
df2 = pd.DataFrame({"A":[2,3,4,5], "B":["A","C","E","F"]})
pd.concat([df1,df2],axis = 1,keys= ["anjali","umang"])

  anjali    umang
       A  B     A  B
0      2  A     2  A
1      3  B     3  C
2      4  C     4  E
3      5  D     5  F

In [ ]:
df1 = pd.DataFrame({"A":[2,3,4,5], "B":["A","B","C","D"]})
df2 = pd.DataFrame({"A":[2,3,4,5], "B":["A","C","E","F"]})
pd.concat([df1,df2],axis = 0,keys= ["anjali","umang"])

          A  B
anjali 0  2  A
       1  3  B
       2  4  C
       3  5  D
umang  0  2  A
       1  3  C
       2  4  E
       3  5  F

In [ ]:
df1 = pd.DataFrame({"A":[2,3,4,5]})
df2 = pd.DataFrame({"A":[2,3,4,5], "B":["A","C","E","F"]})
pd.concat([df1,df2],axis = 1)

   A  A  B
0  2  2  A
1  3  3  C
2  4  4  E
3  5  5  F

In [ ]:
df1 = pd.DataFrame({"A":[2,3,4,5]})
df2 = pd.DataFrame({"A":[2,3,4,5], "B":["A","C","E","F"]})
pd.concat([df1,df2],axis = 0,)

   A    B
0  2  NaN
1  3  NaN
2  4  NaN
3  5  NaN
0  2    A
1  3    C
2  4    E
3  5    F

In [ ]:
df1 = pd.DataFrame({"A":[2,3,4,5], "B":["A","B","C","D"]})
df2 = pd.DataFrame({"A":[20,30], "B":["A","B"]})
pd.concat([df1,df2],axis = 1)

   A  B     A    B
0  2  A  20.0    A
1  3  B  30.0    B
2  4  C   NaN  NaN
3  5  D   NaN  NaN

In [ ]:
df1 = pd.DataFrame({"A":[2,3,4,5], "B":["A","B","C","D"]})
df2 = pd.DataFrame({"A":[20,30], "B":["A","B"]})
pd.concat([df1,df2],axis = 0)

    A  B
0   2  A
1   3  B
2   4  C
3   5  D
0  20  A
1  30  B